config/routes.rb
Rails.application.routes.draw do
  resources :workers
  resources :administrators
  resources :desks
  resources :bookings
  devise_for :users
  get 'static_pages/welcome'
  get 'welcome', to: 'static_pages#welcome', as: 'welcome'
  get 'about', to: 'static_pages#about', as: 'about'
  root to: redirect('/welcome', status: 302)
  get 'reservation', to: 'static_pages#reservation', as: 'reservation'
  get 'login', to: 'static_pages#login', as: 'login'
  get 'welcome_name', to: 'static_pages#welcome_name', as: 'welcome_name'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/desk.rb
class Desk < ApplicationRecord
    has_many :bookings
   
end

app/controllers/desks_controller.rb
class DesksController < ApplicationController
  before_action :set_desk, only: %i[ show edit update destroy ]

  # GET /desks or /desks.json
  def index
    @desks = Desk.all
   
  end

  # GET /desks/1 or /desks/1.json
  def show
  end

  # GET /desks/new
  def new
    @desk = Desk.new
  end

  # GET /desks/1/edit
  def edit
  end

  # POST /desks or /desks.json
  def create
    @desk = Desk.new(desk_params)

    respond_to do |format|
      if @desk.save
        format.html { redirect_to desk_url(@desk), notice: "Desk was successfully created." }
        format.json { render :show, status: :created, location: @desk }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @desk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /desks/1 or /desks/1.json
  def update
    respond_to do |format|
      if @desk.update(desk_params)
        format.html { redirect_to desk_url(@desk), notice: "Desk was successfully updated." }
        format.json { render :show, status: :ok, location: @desk }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @desk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /desks/1 or /desks/1.json
  def destroy
    @desk.destroy

    respond_to do |format|
      format.html { redirect_to desks_url, notice: "Desk was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_desk
      @desk = Desk.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def desk_params
      params.require(:desk).permit(:DeskID, :Availability, :Description)
    end

    
end

app/helpers/desks_helper.rb
module DesksHelper
end

app/views/desks/_desk.html.erb
<!-- app/views/desks/_desk.html.erb -->
<div id="<%= dom_id desk %>" class="desk-details">
  <p>
    <strong>Desk ID:</strong>
    <%= desk.DeskID %>
  </p>

  <p>
    <strong>Dostępność:</strong>
    <%= desk.availability %>
  </p>

  <p>
    <strong>Opis:</strong>
    <%= desk.Description %>
  </p>
</div>

<div class="actions">
  <%= link_to "Edytuj szczegóły", edit_desk_path(desk), class: "edit-link" %> |
  <%= link_to "Pokaż szczegóły", desk, class: "show-link" %> |
  <%= button_to "Usuń to biurko", desk, method: :delete, class: "delete-button" %>
</div>

app/views/desks/_form.html.erb
<!-- app/views/desks/_form.html.erb -->
<%= form_with(model: desk) do |form| %>
  <% if desk.errors.any? %>
    <div class="error-message">
      <h2><%= pluralize(desk.errors.count, "error") %> prohibited this desk from being saved:</h2>

      <ul>
        <% desk.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :DeskID, class: "form-label" %>
    <%= form.text_field :DeskID, class: "form-input" %>
  </div>

  <div>
    <%= form.label :availability, class: "form-label" %>
    <%= form.text_field :availability, class: "form-input" %>
  </div>

  <div>
    <%= form.label :Description, class: "form-label" %>
    <%= form.text_field :Description, class: "form-input" %>
  </div>

  <div>
    <%= form.submit class: "form-submit" %>
  </div>
<% end %>

app/views/desks/edit.html.erb
<h1>Edytuj szczegóły</h1>

<%= render "form", desk: @desk %>
<div>

  <%= link_to "Powrót do biurek", desks_path %>
</div>

app/views/desks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Biurka</h1>

<div id="desks">
  <% @desks.each do |desk| %>
    <%= render desk %>
    
  <% end %>
</div>

<%= link_to "Nowe biurko", new_desk_path %>

app/views/desks/new.html.erb
<h1>Nowe biurko</h1>

<%= render "form", desk: @desk %>

<br>

<div>
  <%= link_to "Powrót do biurek", desks_path %>
</div>

app/views/desks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @desk %>

<div>
  <%= link_to "Powrót do biurek", desks_path %>


</div>