config/routes.rb
Rails.application.routes.draw do
  resources :workers
  resources :administrators
  resources :desks
  resources :bookings
  devise_for :users
  get 'static_pages/welcome'
  get 'welcome', to: 'static_pages#welcome', as: 'welcome'
  get 'about', to: 'static_pages#about', as: 'about'
  root to: redirect('/welcome', status: 302)
  get 'reservation', to: 'static_pages#reservation', as: 'reservation'
  get 'login', to: 'static_pages#login', as: 'login'
  get 'welcome_name', to: 'static_pages#welcome_name', as: 'welcome_name'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/administrator.rb
class Administrator < ApplicationRecord
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  before_action :set_administrator, only: %i[ show edit update destroy ]

  # GET /administrators or /administrators.json
  def index
    @administrators = Administrator.all
  end

  # GET /administrators/1 or /administrators/1.json
  def show
  end

  # GET /administrators/new
  def new
    @administrator = Administrator.new
  end

  # GET /administrators/1/edit
  def edit
  end

  # POST /administrators or /administrators.json
  def create
    @administrator = Administrator.new(administrator_params)

    respond_to do |format|
      if @administrator.save
        format.html { redirect_to administrator_url(@administrator), notice: "Administrator was successfully created." }
        format.json { render :show, status: :created, location: @administrator }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administrators/1 or /administrators/1.json
  def update
    respond_to do |format|
      if @administrator.update(administrator_params)
        format.html { redirect_to administrator_url(@administrator), notice: "Administrator was successfully updated." }
        format.json { render :show, status: :ok, location: @administrator }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administrators/1 or /administrators/1.json
  def destroy
    @administrator.destroy

    respond_to do |format|
      format.html { redirect_to administrators_url, notice: "Administrator was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administrator
      @administrator = Administrator.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def administrator_params
      params.require(:administrator).permit(:AdminID, :Password)
    end
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/views/administrators/_administrator.html.erb
<div id="<%= dom_id administrator %>">
  <p>
    <strong>AdminID:</strong>
    <%= administrator.AdminID %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= administrator.Password %>
  </p>

</div>
<div class="actions">
  <%= link_to "Edytuj szczegóły", edit_administrator_path(administrator), class: "edit-link" %> 
  <%= link_to "Pokaż szczegóły", administrator, class: "show-link" %> 
  
</div>

app/views/administrators/_form.html.erb
<%= form_with(model: administrator) do |form| %>
  <% if administrator.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(administrator.errors.count, "error") %> prohibited this administrator from being saved:</h2>
      <ul>
        <% administrator.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :AdminID, "Administrator ID" %>
    <%= form.text_field :AdminID, class: "form-control", placeholder: "Enter Administrator ID" %>
  </div>

  <div class="form-group">
    <%= form.label :Password, "Password" %>
    <%= form.text_field :Password, class: "form-control", placeholder: "Enter Password" %>
  </div>

  <div class="form-group">
    <%= form.submit "Zapisz", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/administrators/edit.html.erb
<h1>Edytuj administrtora</h1>

<%= render "form", administrator: @administrator %>

<br>

<div>
  <%= link_to "Powrót do administratorów", administrators_path %>
</div>

app/views/administrators/index.html.erb
<head>
  <!-- Inne tagi head... -->
  <%= stylesheet_link_tag 'administrators' %>
</head>

<p class="success-message"><%= notice %></p>





<h1>Administratorzy</h1>

<div id="administrators" class="administrators-list">
  <% @administrators.each do |administrator| %>
    <div class="administrator-item">
      <%= render administrator %>
    
    </div>
  <% end %>
</div>


<%= link_to "Nowy administrator", new_administrator_path, class: "new-administrator-link" %>

app/views/administrators/new.html.erb
<h1>Nowy administrator</h1>

<%= render "form", administrator: @administrator %>

<br>

<div>
  <%= link_to "Powrót do administratorów", administrators_path %>
</div>

app/views/administrators/show.html.erb
<!-- app/views/administrators/show.html.erb -->
<p style="color: green"><%= notice %></p>

<div class="administrator-details">
  <p>
    <strong>AdminID:</strong>
    <%= @administrator.AdminID %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= @administrator.Password %>
  </p>

  <!-- Dodaj inne szczegóły administratora, jeśli są dostępne -->
</div>

<div class="actions">
  <%= link_to "Edytuj szczegóły", edit_administrator_path(@administrator), class: "edit-button" %> |
  

  <%= button_to "Usuń tego administratora", @administrator, method: :delete, class: "delete-button" %>
  <%= link_to "Powrót do administratorów", administrators_path, class: "back-button" %>
</div>