config/routes.rb
Rails.application.routes.draw do
  resources :workers
  resources :administrators
  resources :desks
  resources :bookings
  devise_for :users
  get 'static_pages/welcome'
  get 'welcome', to: 'static_pages#welcome', as: 'welcome'
  get 'about', to: 'static_pages#about', as: 'about'
  root to: redirect('/welcome', status: 302)
  get 'reservation', to: 'static_pages#reservation', as: 'reservation'
  get 'login', to: 'static_pages#login', as: 'login'
  get 'welcome_name', to: 'static_pages#welcome_name', as: 'welcome_name'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/worker.rb
class Worker < ApplicationRecord
    has_many :bookings
    belongs_to :user
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: %i[ show edit update destroy ]

  # GET /workers or /workers.json
  def index
    @workers = Worker.all
  end

  # GET /workers/1 or /workers/1.json
  def show
  end

  # GET /workers/new
  def new
    @worker = Worker.new
  end

  # GET /workers/1/edit
  def edit
  end

  # POST /workers or /workers.json
  def create
    @worker = Worker.new(worker_params)

    respond_to do |format|
      if @worker.save
        format.html { redirect_to worker_url(@worker), notice: "Worker was successfully created." }
        format.json { render :show, status: :created, location: @worker }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workers/1 or /workers/1.json
  def update
    respond_to do |format|
      if @worker.update(worker_params)
        format.html { redirect_to worker_url(@worker), notice: "Worker was successfully updated." }
        format.json { render :show, status: :ok, location: @worker }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers/1 or /workers/1.json
  def destroy
    @worker.destroy

    respond_to do |format|
      format.html { redirect_to workers_url, notice: "Worker was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def worker_params
      params.require(:worker).permit(:WorkerID, :Password)
    end
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/workers/_form.html.erb
<!-- app/views/workers/_form.html.erb -->
<%= form_with(model: worker) do |form| %>
  <% if worker.errors.any? %>
    <div class="error-message">
      <h2><%= pluralize(worker.errors.count, "error") %> prohibited this worker from being saved:</h2>

      <ul>
        <% worker.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :WorkerID, class: "form-label" %>
    <%= form.text_field :WorkerID, class: "form-input" %>
  </div>

  <div>
    <%= form.label :Password, class: "form-label" %>
    <%= form.text_field :Password, class: "form-input" %>
  </div>

  <!-- Dodaj inne pola formularza, jeśli są potrzebne -->

  <div>
    <%= form.submit class: "form-submit" %>
  </div>
<% end %>

app/views/workers/_worker.html.erb
<!-- app/views/workers/_worker.html.erb -->
<div id="<%= dom_id worker %>" class="worker-details">
  <p>
    <strong>Worker ID:</strong>
    <%= worker.WorkerID %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= worker.Password %>
  </p>

  <!-- Dodaj inne szczegóły pracownika, jeśli są dostępne -->
</div>

<% if params[:action] == 'index' %>
  <div class="actions">
    <%= link_to "Edytuj szczegóły", edit_worker_path(worker), class: "edit-link" %> |
    <%= link_to "Pokaż szczegóły", worker, class: "show-link" %> |
    <%= button_to "Usuń tego pracownika", worker, method: :delete, class: "delete-button" %>
  </div>
<% elsif params[:action] == 'show' %>
  <div>
    <%= link_to "Edytuj szczegóły", edit_worker_path(worker), class: "edit-link" %> 
   
    <%= button_to "Usuń tego pracownika", worker, method: :delete, class: "delete-button" %>
     <%= link_to "Powrót do pracowników", workers_path %>

  </div>
<% end %>

app/views/workers/edit.html.erb
<h1>Edytuj szczegóły</h1>

<%= render "form", worker: @worker %>

<br>

<div>
  <%= link_to "Powrót do pracowników", workers_path %>
</div>

app/views/workers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pracownicy</h1>

<div id="workers">
  <% @workers.each do |worker| %>
    <%= render worker %>
    
  <% end %>
</div>

<%= link_to "Nowy pracownik", new_worker_path %>

app/views/workers/new.html.erb
<h1>Nowy pracownik</h1>

<%= render "form", worker: @worker %>

<br>

<div>
  <%= link_to "Powrót do pracowników", workers_path %>
</div>

app/views/workers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @worker %>

<br>

<div>


</div>