config/routes.rb
Rails.application.routes.draw do
  resources :workers
  resources :administrators
  resources :desks
  resources :bookings
  devise_for :users
  get 'static_pages/welcome'
  get 'welcome', to: 'static_pages#welcome', as: 'welcome'
  get 'about', to: 'static_pages#about', as: 'about'
  root to: redirect('/welcome', status: 302)
  get 'reservation', to: 'static_pages#reservation', as: 'reservation'
  get 'login', to: 'static_pages#login', as: 'login'
  get 'welcome_name', to: 'static_pages#welcome_name', as: 'welcome_name'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_navbar_logged_in.html.erb
<nav class="navbar navbar-expand-lg bg-light" data-bs-theme="light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Book a desk</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor03">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to 'Home', welcome_path, class: 'nav-link' %>
          <span class="visually-hidden">(current)</span>
        </li>
        <li class="nav-item">
          <%= link_to 'Mapa', reservation_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Rezerwacje', bookings_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'O nas', about_path, class: 'nav-link' %>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-sm-2" type="search" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>
      <div class="btn btn-success">
        <%= button_to "Wyloguj się", destroy_user_session_path, method: :delete, :class => "btn btn-success" %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_navbar_logged_in_admin.html.erb
<nav class="navbar navbar-expand-lg bg-light" data-bs-theme="light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Book a desk (Administrator)</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor03">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to 'Home', welcome_path, class: 'nav-link' %>
          <span class="visually-hidden">(current)</span>
        </li>
        <li class="nav-item">
          <%= link_to 'Mapa', reservation_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Pracownicy', workers_path, class: 'nav-link' %>
        </li>
         <li class="nav-item">
          <%= link_to 'Administratorzy', administrators_path, class: 'nav-link' %>
        </li>
        </li>
         <li class="nav-item">
          <%= link_to 'Biurka', desks_path, class: 'nav-link' %>
        </li>
          </li>
          <li class="nav-item">
          <%= link_to 'Rezerwacje', bookings_path, class: 'nav-link' %>
        </li>
         <li class="nav-item">
          <%= link_to 'O nas', about_path, class: 'nav-link' %>
        </li>
        
      </ul>
      
      <div class="btn btn-success">
        <%= button_to "Wyloguj się", destroy_user_session_path, method: :delete, :class => "btn btn-success" %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Book a desk</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>



<!DOCTYPE html>
<html>
  <head>
    <title>Book a desk</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if user_signed_in? %>

       <% if current_user.email == '4999@admin.com' %>
       <%= render 'layouts/navbar_logged_in_admin' %>
       <% else %>
       <%= render 'layouts/navbar_logged_in' %>
      <% end %>

  
      <% else %>

      <nav class="navbar navbar-expand-lg bg-light" data-bs-theme="light">
      <div class="container-fluid">
      <a class="navbar-brand" href="#">Book a desk</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarColor03">
      <ul class="navbar-nav me-auto">

        <li class="nav-item">
          <%= link_to 'Home', welcome_path, class: 'nav-link' %>
            <span class="visually-hidden">(current)</span>
          </a>
        </li>

        <li class="nav-item">
          <%= link_to 'O nas', about_path, class: 'nav-link' %>
        </li>

      <div class="btn btn-success" style="float: right;">
      <%= button_to "Zaloguj się", new_user_session_path, :class => "btn btn-success"  %>
      </div>

      <% end %>
      </div>
      </div>

</nav>
    <%= yield %>
  </body>
</html>